export const profile = {
  name: "Alamu Joseph",
  handle: "alamu_joseph",
  role: "Cybersecurity Analyst",
  location: "Ibadan, Nigeria",
  address: "Ibadan, Oyo State, Nigeria",
  email: "alamujosephlegacy@gmail.com",
  phone: "+234 814 918 9165",
  phoneHref: "+2348149189165",
  linkedin: "https://www.linkedin.com/in/alamu-joseph",
  github: "https://github.com/AJ-legends",
  bio: "Computer Science undergraduate at Covenant University working across offensive and defensive security — VAPT with Nmap, Metasploit and Burp Suite, AWS infrastructure, and privacy-preserving systems built on homomorphic encryption.",
  verbs: ["ATTACK", "DEFEND", "AUTOMATE"],
  stats: [
    { value: "4.93", label: "CGPA / 5.0" },
    { value: "13", label: "Lab environments assessed" },
    { value: "06", label: "Certifications earned" },
    { value: "PY", label: "Primary language" },
  ],
  skills: [
    "Penetration Testing",
    "Vulnerability Assessment",
    "Digital Forensics",
    "Homomorphic Encryption",
    "Nmap / Metasploit / Burp Suite",
    "Wireshark / Gobuster / Hydra",
    "AWS EC2, S3, IAM, VPC",
    "Linux & Windows Server",
    "Python, TypeScript, SQL",
  ],
  skillGroups: [
    {
      id: "offensive",
      label: "Offensive Security",
      note: "Breaking things in a lab so I understand how they fail.",
      axes: [
        { label: "Recon (Nmap)", value: 84 },
        { label: "Metasploit", value: 80 },
        { label: "Burp Suite", value: 72 },
        { label: "Priv. Esc.", value: 74 },
        { label: "Password Attacks", value: 70 },
        { label: "Reporting", value: 76 },
      ],
    },
    {
      id: "defensive",
      label: "Defensive Security",
      note: "Detection, hardening and incident fundamentals.",
      axes: [
        { label: "Vuln. Assessment", value: 82 },
        { label: "Hardening", value: 72 },
        { label: "Log Analysis", value: 74 },
        { label: "Access Control", value: 76 },
        { label: "Digital Forensics", value: 66 },
        { label: "Defense Evasion", value: 68 },
      ],
    },
    {
      id: "cloud",
      label: "Cloud & Infrastructure",
      note: "Deploying and securing workloads on AWS and Linux.",
      axes: [
        { label: "AWS EC2", value: 78 },
        { label: "S3", value: 74 },
        { label: "IAM", value: 72 },
        { label: "VPC / SGs", value: 70 },
        { label: "CloudWatch", value: 66 },
        { label: "Linux Admin", value: 82 },
      ],
    },
    {
      id: "networking",
      label: "Networking",
      note: "Reading traffic at the byte level.",
      axes: [
        { label: "TCP/IP", value: 82 },
        { label: "Wireshark", value: 78 },
        { label: "DNS/HTTP", value: 74 },
        { label: "Monitoring", value: 76 },
        { label: "Troubleshooting", value: 80 },
        { label: "VMware/VBox", value: 78 },
      ],
    },
    {
      id: "programming",
      label: "Programming",
      note: "Python first, automation always.",
      axes: [
        { label: "Python", value: 88 },
        { label: "TypeScript", value: 76 },
        { label: "SQL", value: 70 },
        { label: "Automation", value: 82 },
        { label: "Cryptography", value: 72 },
        { label: "Git", value: 72 },
      ],
    },
  ],
  education: [
    {
      school: "Covenant University",
      place: "Ota, Ogun State",
      degree: "B.Sc. Computer Science",
      period: "In progress",
      note: "CGPA 4.93 / 5.0 — Computer Security, Operating Systems, Algorithms & Data Structures, OOP",
    },
  ],
  experience: [
    {
      company: "LPI Innovation Hub",
      role: "IT Intern",
      place: "Ibadan",
      period: "Mar 2025 — Sep 2025",
      points: [
        "Performed vulnerability assessments and penetration testing using Nmap and Metasploit, identifying and validating vulnerabilities across 13 laboratory environments.",
        "Deployed Ubuntu Linux on standard workstations and configured Kali Linux environments for VAPT.",
        "Researched AI-related cybersecurity risks and contributed to technical documentation promoting security awareness and responsible AI usage.",
        "Supported day-to-day network monitoring, troubleshooting and IT helpdesk operations.",
      ],
    },
  ],
  projects: [
    {
      slug: "secure-sis",
      name: "Secure Student Information System",
      cmd: "npm run start -- --crypto paillier --host ec2",
      description:
        "A full-stack student information system built with React, TypeScript, Express.js and SQLite, integrating the Paillier cryptosystem for privacy-preserving computation over encrypted student records. The backend uses JWT authentication, role-based authorization and homomorphic encryption services so academic data is processed and decrypted without exposing it to the application layer.",
      tags: [
        "React",
        "TypeScript",
        "Express.js",
        "SQLite",
        "AWS EC2 / S3",
        "Paillier Cryptosystem",
      ],
      log: [
        "[+] paillier keypair generated — 2048 bit",
        "[*] encrypted aggregate over 412 records",
        "[+] jwt auth + rbac enforced",
        "[i] plaintext never leaves the crypto layer",
      ],
    },
    {
      slug: "windows-vm-pentest",
      name: "Windows VM Penetration Test",
      cmd: "msfconsole -q -x 'use exploit/windows/local/...'",
      description:
        "Full penetration tests against a Windows 11 VM and Metasploitable 2 — exploiting vulnerabilities and practising privilege escalation, defense evasion and post-exploitation. Also competed in a GDG campus challenge, identifying and exploiting a vulnerability in a navigator application in a controlled CTF-style environment.",
      tags: ["Metasploit", "Kali Linux", "Windows 11", "Metasploitable 2", "VirtualBox"],
      log: [
        "[*] exploit completed — meterpreter session 1 opened",
        "[+] getsystem — NT AUTHORITY\\SYSTEM",
        "[*] av evasion payload staged",
        "[+] post-exploitation loot collected",
      ],
    },
    {
      slug: "keylogger",
      name: "Keylogger — Keystroke Monitoring Tool",
      cmd: "./keylog.py --research-mode --out ./lab/session.log",
      description:
        "A Python-based keylogger written for ethical offensive-security research: capturing keystrokes and monitoring system activity inside isolated lab environments to study attacker techniques and inform defensive countermeasures.",
      tags: ["Python", "Input hooks", "Offensive research", "Detection"],
      log: [
        "[*] research mode — isolated lab only",
        "[+] hook attached to input layer",
        "[*] writing to ./lab/session.log",
        "[i] mitigation notes: 04",
      ],
    },
  ],
  certifications: [
    {
      name: "Ethical Hacking",
      issuer: "Cisco Networking Academy",
      year: "2025",
      note: "Reconnaissance, exploitation, post-exploitation and reporting methodology.",
    },
    {
      name: "Cybersecurity Essentials",
      issuer: "Cisco Networking Academy",
      year: "2024",
      note: "Threat landscape, cryptography, access control and defensive fundamentals.",
    },
    {
      name: "Python Essentials",
      issuer: "Cisco Networking Academy",
      year: "2024",
      note: "Core Python syntax, data structures and control flow.",
    },
    {
      name: "IT Essentials",
      issuer: "Cisco Networking Academy",
      year: "2024",
      note: "Hardware, operating systems, networking and IT support operations.",
    },
    {
      name: "Microsoft Office Specialist: Office 2019",
      issuer: "Microsoft",
      year: "2023",
      note: "Certified proficiency across the Microsoft Office productivity suite.",
    },
    {
      name: "Prompt Engineering for LLMs",
      issuer: "OBTranslate",
      year: "2025",
      note: "Structured prompting, model behaviour and applied LLM workflows.",
    },
  ],
};

export type Profile = typeof profile;
